name: artisan
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  substring_highlight: ^1.0.33
  lottie: ^1.2.2
  shared_preferences: ^2.0.15
  sliding_up_panel2: ^3.2.2
  searchfield: ^0.6.6
  http: ^0.13.5
  auto_size_text: ^3.0.0
  another_flushbar: ^1.10.29
  google_maps_flutter: ^2.1.12
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.2.6


flutter_native_splash:
      color: "#5F9221"
      android: true
      ios: true
      web: false
      image: assets/images/logo.png
      android_12:
        color: "#5F9221"
        image: assets/images/logo.png
        icon_background_color: "#111111"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/images/populars/
   - assets/images/search/
   - assets/animations/
 

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
